FROM node:20.17-alpine AS base

FROM base as dev
WORKDIR /app
ADD package*.json ./
ENV NODE_ENV=development
RUN npm ci

ADD . .

EXPOSE 3333

CMD ["node", "ace", "migration:run"]
CMD ["node", "ace", "serve", "--watch"]

